### ISSUE TITLE
Donate Page Value Select

### ISSUE THREAD

**Issue by fischfood** [nate-allen/peerraiser#1]
While on the /donate page, by clicking a pre-determined amount, then going to the input fielding and changing the value, the originally selection does not get reset (it shows as still clicked). Also as a reverse, if I put in a specific dollar amount, then click a button, my original amount is still shown in the field instead of being replaced by the button number or reset to blank

**Comment by nate-allen** [comment]
So I tested this locally and it actually seems to be working correctly. I wonder if there was a JavaScript error on the page that was causing it to not work?

**Comment by nate-allen** [comment]
Confirmed this was a JavaScript error caused by the site's theme and not PeerRaiser. 👍
